# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/EzDomain.EventSourcing
      - src/EzDomain.EventSourcing.Tests
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
name: 2.0$(rev:.r)

steps:
- script: echo '$(Build.BuildNumber)'
- task: NuGetCommand@2
  displayName: 'Run Restore'
  inputs:
    command: 'restore'
    projects: |
      src/EzDomain.EventSourcing/EzDomain.EventSourcing.csproj
      src/EzDomain.EventSourcing.Tests/EzDomain.EventSourcing.Tests.csproj
- task: DotNetCoreCLI@2
  displayName: 'Run Build'
  inputs:
    command: 'build'
    projects: src/EzDomain.EventSourcing/EzDomain.EventSourcing.csproj
    arguments: --configuration $(BuildConfiguration)
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: 'src/EzDomain.EventSourcing.Tests/EzDomain.EventSourcing.Tests.csproj'
    arguments: --configuration $(BuildConfiguration)
- task: DotNetCoreCLI@2
  displayName: 'NuGet Pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/EzDomain.EventSourcing/EzDomain.EventSourcing.csproj'
    packDirectory: 'src/EzDomain.EventSourcing/bin/$(BuildConfiguration)/netstandard2.0'
    versioningScheme: 'byBuildNumber'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: 'src/EzDomain.EventSourcing/bin/$(BuildConfiguration)/netstandard2.0'
    ArtifactName: 'drop'
    publishLocation: 'Container'